### ISSUE TITLE
How to choose the model ?

### ISSUE THREAD

**Issue by juntaosun** [EnVision-Research/Lotus#5]
|CHECKPOINT_DIR |TASK_NAME |MODE |
|:--:|:--:|:--:|
| `jingheya/lotus-depth-g-v1-0`| `depth`| `generation`|
| `jingheya/lotus-depth-d-v1-0`| `depth`|`regression` |
| `jingheya/lotus-normal-g-v1-0`|`normal` | `generation`|
| `jingheya/lotus-normal-d-v1-0`|`normal` |`regression` |

In addition, running "jingheya/lotus-depth-g-v1-0" takes up all the 12G graphics card memory. 
Is there any way to reduce the configuration or model parameters so that it can run on an 8G graphics card?

**Comment by BlingHe** [comment]
Thanks for your interest in our work!

1. Our inference code is built upon PyTorch 2.3.1, which already supports memory-efficient attention to help reduce memory usage. If you'd like to further minimize memory consumption, you can refer to [this page](https://huggingface.co/docs/diffusers/optimization/memory) for additional guidance.

2. Great question regarding video depth estimation. Currently, Lotus focuses on single-frame images, but we are actively investigating the consistency challenges in video depth estimation. 

Hope my answer helps!

**Comment by haodong2000** [comment]
Hi @juntaosun , thanks so much for your attention!

I have also noticed the flikering during the inference for video depth estimations. Here is also an interesting [tweet (X)](https://x.com/chrisoffner3d/status/1846203943514235172).

From my perspective, perhaps it is because the normalization of V-KITTI is conducted in a per-frame level. We are trying to re-train the model using a scene-level normalization. Hope the video version of LOTUS will be ready soon!

Thanks,
Haodong
